services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./Nuggets.API:/src/Nuggets.API   # only if you want local hot reload/mounting
      - ./Nuggets.Application:/src/Nuggets.Application
      - ./Nuggets.Domain:/src/Nuggets.Domain
      - ./Nuggets.Infrastructure:/src/Nuggets.Infrastructure
