services:
  api:
    build:
      context: .
      dockerfile: Nuggets.API/Dockerfile
    container_name: nuggets_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=nuggets_erp;Username=postgres;Password=postgres
      - Jwt__SigningKey=nkg3*2kln3)!35G
      - Jwt__Issuer=nuggets
      - Jwt__Audience=nuggets_clients
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: nuggets_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nuggets_erp
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
