services:
  api:
    build:
      context: .
      dockerfile: Nuggets.API/Dockerfile
    container_name: nuggets_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=nuggets_erp;Username=postgres;Password=postgres
    depends_on:
      - postgres