namespace Nuggets.Domain.Authorization;

public static class RolePermissions
{
    // Master dictionary
    public static readonly Dictionary<string, string[]> PermissionsByRole = new()
    {
        ["Admin"] = AllPermissions(),
        ["Sales"] =
        [
            "CUSTOMERS:READ", "CUSTOMERS:CREATE", "CUSTOMERS:UPDATE", "CUSTOMERS:DELETE",
            "SUPPLIERS:READ", "SUPPLIERS:CREATE", "SUPPLIERS:UPDATE", "SUPPLIERS:DELETE",
            "SALES:READ", "SALES:CREATE", "SALES:UPDATE", "SALES:DELETE",
            "EXPENSES:READ", "EXPENSES:CREATE", "EXPENSES:UPDATE", "EXPENSES:DELETE",
        ],
        ["Warehouse"] =
        [
            "CUSTOMERS:READ", "CUSTOMERS:CREATE", "CUSTOMERS:UPDATE", "CUSTOMERS:DELETE",
            "SUPPLIERS:READ", "SUPPLIERS:CREATE", "SUPPLIERS:UPDATE", "SUPPLIERS:DELETE",
            "PRODUCTS:READ", "PRODUCTS:CREATE", "PRODUCTS:UPDATE", "PRODUCTS:DELETE",
            "PRODUCT_CATEGORIES:READ", "PRODUCT_CATEGORIES:CREATE", "PRODUCT_CATEGORIES:UPDATE", "PRODUCT_CATEGORIES:DELETE",
            "FOOD_RECIPES:READ", "FOOD_RECIPES:CREATE", "FOOD_RECIPES:UPDATE", "FOOD_RECIPES:DELETE",
            "FOOD_MATERIALS:READ", "FOOD_MATERIALS:CREATE", "FOOD_MATERIALS:UPDATE", "FOOD_MATERIALS:DELETE"
        ],
    };

    public static string[] AllPermissions() =>
    [
        "CUSTOMERS:READ", "CUSTOMERS:CREATE", "CUSTOMERS:UPDATE", "CUSTOMERS:DELETE",
        "SUPPLIERS:READ", "SUPPLIERS:CREATE", "SUPPLIERS:UPDATE", "SUPPLIERS:DELETE",
        "USERS:READ", "USERS:CREATE", "USERS:UPDATE", "USERS:DELETE",
        "PRODUCTS:READ","PRODUCTS:CREATE","PRODUCTS:UPDATE","PRODUCTS:DELETE",
        "PRODUCT_CATEGORIES:READ", "PRODUCT_CATEGORIES:CREATE", "PRODUCT_CATEGORIES:UPDATE", "PRODUCT_CATEGORIES:DELETE",
        "SALES:READ","SALES:CREATE","SALES:UPDATE","SALES:DELETE",
        "EXPENSES:READ", "EXPENSES:CREATE", "EXPENSES:UPDATE", "EXPENSES:DELETE",
        "FOOD_RECIPES:READ","FOOD_RECIPES:CREATE","FOOD_RECIPES:UPDATE","FOOD_RECIPES:DELETE",
        "FOOD_MATERIALS:READ","FOOD_MATERIALS:CREATE","FOOD_MATERIALS:UPDATE","FOOD_MATERIALS:DELETE"
    ];
}