namespace Nuggets.Domain.Authorization;

public static class RolePermissions
{
    public static readonly Dictionary<string, string[]> PermissionsByRole = new()
    {
        ["Admin"] = AllPermissions(),
        ["Accounting"] =
        [
            "ACCOUNTS:READ", "ACCOUNTS:CREATE", "ACCOUNTS:UPDATE", "ACCOUNTS:DELETE",
            "JOURNAL:READ", "JOURNAL:CREATE", "JOURNAL:UPDATE", "JOURNAL:DELETE",
        ],
        ["Sales"] =
        [
            "CUSTOMERS:READ","CUSTOMERS:CREATE","CUSTOMERS:UPDATE","CUSTOMERS:DELETE",
            "SALES:READ","SALES:CREATE","SALES:UPDATE","SALES:DELETE",
            "INVOICES:READ","INVOICES:CREATE"
        ],
        ["Warehouse"] =
        [
            "VENDORS:READ","VENDORS:CREATE","VENDORS:UPDATE","VENDORS:DELETE",
            "PURCHASES:READ","PURCHASES:CREATE","PURCHASES:UPDATE","PURCHASES:DELETE",
            "INVENTORY:READ","INVENTORY:ADJUST",
            "PRODUCTS:READ","PRODUCTS:CREATE","PRODUCTS:UPDATE","PRODUCTS:DELETE",
            "PRODUCT_CATEGORIES:READ", "PRODUCT_CATEGORIES:CREATE", "PRODUCT_CATEGORIES:UPDATE", "PRODUCT_CATEGORIES:DELETE",
            "FOOD_RECIPES:READ", "FOOD_RECIPES:CREATE", "FOOD_RECIPES:UPDATE", "FOOD_RECIPES:DELETE",
            "FOOD_MATERIALS:READ", "FOOD_MATERIALS:CREATE", "FOOD_MATERIALS:UPDATE", "FOOD_MATERIALS:DELETE"
        ]
    };

    public static string[] AllPermissions() =>
    [
        // Accounting
        "ACCOUNTS:READ", "ACCOUNTS:CREATE", "ACCOUNTS:UPDATE", "ACCOUNTS:DELETE",
        "JOURNAL:READ", "JOURNAL:CREATE", "JOURNAL:UPDATE", "JOURNAL:DELETE",
        
        // Product
        "PRODUCTS:READ","PRODUCTS:CREATE","PRODUCTS:UPDATE","PRODUCTS:DELETE",
        "PRODUCT_CATEGORIES:READ","PRODUCT_CATEGORIES:CREATE","PRODUCT_CATEGORIES:UPDATE","PRODUCT_CATEGORIES:DELETE",

        // Sales & Customers
        "CUSTOMERS:READ","CUSTOMERS:CREATE","CUSTOMERS:UPDATE","CUSTOMERS:DELETE",
        "SALES:READ","SALES:CREATE","SALES:UPDATE","SALES:DELETE",
        "INVOICES:READ","INVOICES:CREATE",

        // Purchases & Vendors
        "VENDORS:READ","VENDORS:CREATE","VENDORS:UPDATE","VENDORS:DELETE",
        "PURCHASES:READ","PURCHASES:CREATE","PURCHASES:UPDATE","PURCHASES:DELETE",

        // Inventory
        "INVENTORY:READ","INVENTORY:ADJUST",

        // Expenses
        "EXPENSES:READ","EXPENSES:CREATE","EXPENSES:UPDATE","EXPENSES:DELETE",

        // Food/Recipes
        "FOOD_RECIPES:READ","FOOD_RECIPES:CREATE","FOOD_RECIPES:UPDATE","FOOD_RECIPES:DELETE",
        "FOOD_MATERIALS:READ","FOOD_MATERIALS:CREATE","FOOD_MATERIALS:UPDATE","FOOD_MATERIALS:DELETE",
        
        // Settings
        "USERS:READ", "USERS:CREATE", "USERS:UPDATE", "USERS:DELETE",
    ];
}